### ISSUE TITLE
Week-over-week data

### ISSUE THREAD

**Issue by bogosj** [grecine/covid_data#16]
I'm envisioning something like a graph with X-axis of sun/mon/tue/wed/thu/fri/sat, Y-axis of # of cases, and then one line for each of the last N weeks.

![image](https://user-images.githubusercontent.com/10186620/100007074-791b2380-2d99-11eb-8512-c6a15778a46c.png)

**Comment by jledwith71** [comment]
Nice idea.  Is the goal to show how much that cases have been rising over the last weeks?

**Comment by bogosj** [comment]
Yes, I think. What I *think* this would help visualize is the slope of the infection curve. When NJ publishes their daily update I've been manually looking at the previous week's same-day-of-the-week number to get a gut feel for how things are progressing.

**Comment by grecine** [comment]
Yup. On it! Also going to make a rate of case change curve.

**Comment by jledwith71** [comment]
I think that people may get lost in the lines.  While necessary for showing the 7 days of the week, the slope is something that brings 1 line to mind.  How about the ole "doubling" or "tripling" every 7 days, 6 days, 5 days, etc?  That has been shown as the dotted line on a log scale graph in the past, but I think the log scale threw people.  Just showing the rate of infection (y-axis) for each day (x-axis), while making the y-axis point be a seven day average might tie that all up nicely.

**Comment by jledwith71** [comment]
and on a linear (not log) scale, if that wasn't clearly stated.

**Comment by grecine** [comment]
> I think that people may get lost in the lines. While necessary for showing the 7 days of the week, the slope is something that brings 1 line to mind. How about the ole "doubling" or "tripling" every 7 days, 6 days, 5 days, etc? That has been shown as the dotted line on a log scale graph in the past, but I think the log scale threw people. Just showing the rate of infection (y-axis) for each day (x-axis), while making the y-axis point be a seven day average might tie that all up nicely.

I agree on the number of lines, and the 'rate of case change' curve I was referring to would be just that. I need to find this metric guide I found that suggested a 3-day slope of the 7-day avg, but I think a 7 day avg slope may be just as useful. 

I think the part that went unmentioned here is what plots are useful/fun for us (or those who are used to reading such things) vs the general public. I finally have some free time (off for a while) so we can hash out what is useful, but from my workflow, I can set up the ability to dump a number of different types of plots & data, and from that what is appropriate for public can be picked from those.

**Comment by grecine** [comment]
Closing because we discussed over text how a separate line plot would look. I right now have two additional plots: 1) Week-over-week change of SMA / 100K, 2) 7d slope of SMA / 100K ([commit 3da336c](https://github.com/grecine/covid_data/commit/3da336c04ba146f1f423bb5abde020a7c5b936b3))

I hope to add the following metrics today, based on the [CDC "SARS-CoV-2 transmission metrics webinar" of July 27](https://www.cdc.gov/coronavirus/2019-ncov/downloads/global-covid-19/SARS-CoV-2-Transmission-Metrics.pdf) (pg 27-45). Although these metrics are simplistic, we can modify them for our use case (particularly, how they calc the slop irks me, but I don't know why, exactly). However, they have a nice statement of thresholds for doing a color coded snapshot metric.

I'll make a new issue about doing a RAG-type system for both incident and trajectory.

@bogosj, as always, feel free to re-open if you really want the curve produced as you have above. I can do it for the past N weeks, I'd just like to get the other metrics above done first.
